<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CommissionerSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('nec_commissioners')->truncate();

        $now = now();

        $commissioners = [
            [
                'name'              => 'Hon. Prof. Abednego Akok Kacuol',
                'title'             => 'Prof.',
                'gender'            => 'male',
                'position'          => 'Chairperson',
                'date_of_birth'     => '1955-01-01',
                'nationality'       => 'South Sudanese',
                'email'             => 'chairperson@nec.gov.ss',
                'phone'             => '+211 912 000 001',
                'bio'               => 'Chairperson of the National Elections Commission, leading the supervision of free, fair and transparent elections in South Sudan.',
                'about'             => 'Hon. Prof. Abednego Akok Kacuol is the Chairperson of the National Elections Commission. He was born in Yirol (Mapagic village), Lakes State, Sudan in 1955. He conducts the overall supervision of the NEC and presides over all Board of Commissioner meetings. First appointed as Chairman in August 2012, he represents the NEC in both national and international functions to ensure the Commission\'s role in fostering and strengthening the democratic process in South Sudan.',
                'experience'        => "Chairperson, National Elections Commission (first appointed August 2012)\nRepresentative of the NEC in national and international functions\nOverall supervision of the NEC",
                'qualifications'    => "Professor of Public Administration\nLong-standing academic and public administration career",
                'achievements'      => "Strengthened NEC's role in fostering the democratic process in South Sudan\nLed the Commission through multiple electoral cycles",
                'photo'             => 'assets/images/leadership/chairperson.jpg',
                'facebook_url'      => null,
                'twitter_url'       => null,
                'linkedin_url'      => null,
                'website_url'       => null,
                'years_of_service'  => 14,
                'department'        => 'Office of the Chairperson',
                'order_num'         => 1,
                'featured'          => true,
                'status'            => 'active',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Hon. Dr. Francis Luigi Adwok',
                'title'             => 'Dr.',
                'gender'            => 'male',
                'position'          => 'Deputy Chairperson',
                'date_of_birth'     => null,
                'nationality'       => 'South Sudanese',
                'email'             => 'deputy.chairperson@nec.gov.ss',
                'phone'             => '+211 912 000 002',
                'bio'               => 'Deputy Chairperson of the National Elections Commission, sworn in on 3 July 2026.',
                'about'             => 'Hon. Dr. Francis Luigi Adwok is the Deputy Chairperson of the National Elections Commission. He was sworn in on July 3, 2026, and supports the Chairperson in the overall governance and supervision of the Commission.',
                'experience'        => "Deputy Chairperson, National Elections Commission (July 2026 – Present)",
                'qualifications'    => null,
                'achievements'      => null,
                'photo'             => 'assets/images/leadership/deputy-chairperson.jpg',
                'facebook_url'      => null,
                'twitter_url'       => null,
                'linkedin_url'      => null,
                'website_url'       => null,
                'years_of_service'  => 0,
                'department'        => 'Office of the Deputy Chairperson',
                'order_num'         => 2,
                'featured'          => false,
                'status'            => 'active',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Hon. Mach Maika Deng',
                'title'             => 'Hon.',
                'gender'            => 'male',
                'position'          => 'Chief Electoral Officer',
                'date_of_birth'     => null,
                'nationality'       => 'South Sudanese',
                'email'             => 'ceo@nec.gov.ss',
                'phone'             => '+211 912 000 003',
                'bio'               => 'Chief Electoral Officer of the NEC, supervising all electoral activities in accordance with electoral law.',
                'about'             => 'Hon. Mach Maika Deng is a NEC Commissioner and acts as the Chief Electoral Officer of the Commission. He is responsible for the supervision of all electoral-related activities in accordance with the electoral law. Hon. Mach Maika is also the focal point for matters related to election security coordination and coordination with the State High Committees. He has been the CEO of the NEC since August 2012.',
                'experience'        => "Chief Electoral Officer, National Elections Commission (since August 2012)\nFocal point for election security coordination\nCoordination with State High Committees",
                'qualifications'    => null,
                'achievements'      => null,
                'photo'             => 'assets/images/leadership/chief-electoral-officer.jpg',
                'facebook_url'      => null,
                'twitter_url'       => null,
                'linkedin_url'      => null,
                'website_url'       => null,
                'years_of_service'  => 14,
                'department'        => 'Office of the Chief Electoral Officer',
                'order_num'         => 3,
                'featured'          => false,
                'status'            => 'active',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Hon. George Lemi Yata',
                'title'             => 'Hon.',
                'gender'            => 'male',
                'position'          => 'Spokesperson – Commissioner',
                'date_of_birth'     => null,
                'nationality'       => 'South Sudanese',
                'email'             => 'spokesperson@nec.gov.ss',
                'phone'             => '+211 912 000 004',
                'bio'               => 'Spokesperson of the NEC, born in Wau and responsible for the Commission\'s public communications.',
                'about'             => 'Hon. George Lemi Yata is the Spokesperson of the NEC. He was born in Wau, South Sudan, and spent his childhood growing up in Juba before moving to Khartoum. He pursued his studies at Comboni and St. Augustine in Juba and Khartoum, and holds a Diploma in Graphic and Website Design, a B.Sc. in Information Technology, a Diploma in Human Resources Management, and a Postgraduate Diploma in Peace and Development Studies at the University of Juba.',
                'experience'        => "Spokesperson, National Elections Commission",
                'qualifications'    => "Diploma in Graphic and Website Design\nB.Sc. in Information Technology\nDiploma in Human Resources Management\nPostgraduate Diploma in Peace and Development Studies, University of Juba",
                'achievements'      => null,
                'photo'             => 'assets/images/leadership/spokesperson.jpg',
                'facebook_url'      => null,
                'twitter_url'       => null,
                'linkedin_url'      => null,
                'website_url'       => null,
                'years_of_service'  => null,
                'department'        => 'Communications',
                'order_num'         => 4,
                'featured'          => false,
                'status'            => 'active',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Hon. Thabo Abosuh Ajang',
                'title'             => 'Hon.',
                'gender'            => 'female',
                'position'          => 'Commissioner',
                'date_of_birth'     => null,
                'nationality'       => 'South Sudanese',
                'email'             => 'commissioner.civic@nec.gov.ss',
                'phone'             => '+211 912 000 005',
                'bio'               => 'NEC Commissioner responsible for supervision of gender issues and civic and voter education.',
                'about'             => 'Hon. Thabo Abosuh Ajang was born in Yei Town, Central Equatoria State. She graduated from Malakal Shabia Banat School and earned a Degree in Education from Zagazig University in Egypt, majoring in Geography and History (1993). She later taught at Malakal Secondary School and Civil Aviation Girls. First appointed to the NEC in April 2014, Hon. Ajang is the Commissioner responsible for all matters related to the supervision of gender issues, and civic and voter education.',
                'experience'        => "Commissioner, National Elections Commission (first appointed April 2014)\nTeacher, Malakal Secondary School and Civil Aviation Girls (2004 – 2010)",
                'qualifications'    => "Degree in Education, Zagazig University, Egypt (1993)",
                'achievements'      => null,
                'photo'             => 'assets/images/leadership/commissioner-thabo.jpg',
                'facebook_url'      => null,
                'twitter_url'       => null,
                'linkedin_url'      => null,
                'website_url'       => null,
                'years_of_service'  => 12,
                'department'        => 'Civic and Voter Education',
                'order_num'         => 5,
                'featured'          => false,
                'status'            => 'active',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Hon. Josephine Achiro Fortelo',
                'title'             => 'Hon.',
                'gender'            => 'female',
                'position'          => 'Commissioner',
                'date_of_birth'     => null,
                'nationality'       => 'South Sudanese',
                'email'             => 'commissioner.fortelo@nec.gov.ss',
                'phone'             => '+211 912 000 006',
                'bio'               => 'Commissioner of the National Elections Commission.',
                'about'             => 'Hon. Josephine Achiro Fortelo is a Commissioner of the National Elections Commission. She completed her secondary education at Torit Day Senior Secondary School, graduating with the Sudan School Certificate (2007). She then earned a degree in Business Administration from the Catholic University of South Sudan (2013).',
                'experience'        => "Commissioner, National Elections Commission",
                'qualifications'    => "Degree in Business Administration, Catholic University of South Sudan (2013)\nSudan School Certificate, Torit Day Senior Secondary School (2007)",
                'achievements'      => null,
                'photo'             => 'assets/images/leadership/commissioner-josephine.jpg',
                'facebook_url'      => null,
                'twitter_url'       => null,
                'linkedin_url'      => null,
                'website_url'       => null,
                'years_of_service'  => null,
                'department'        => null,
                'order_num'         => 6,
                'featured'          => false,
                'status'            => 'active',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Hon. Sarah Daniel Gatluak',
                'title'             => 'Hon.',
                'gender'            => 'female',
                'position'          => 'Commissioner',
                'date_of_birth'     => null,
                'nationality'       => 'South Sudanese',
                'email'             => 'commissioner.gatluak@nec.gov.ss',
                'phone'             => '+211 912 000 007',
                'bio'               => 'NEC Commissioner appointed on 8 January 2024, formerly a member of Parliament.',
                'about'             => 'Hon. Sarah Daniel Gatluak was born in Nasir town, Upper Nile State. She studied and graduated from Assas Binat in Khartoum. After completing her studies, she entered public service and was appointed to Parliament in 2010, where she served until joining the National Elections Commission as Commissioner on January 8, 2024.',
                'experience'        => "Commissioner, National Elections Commission (January 2024 – Present)\nMember of Parliament (2010 – 2024)",
                'qualifications'    => "Graduate, Assas Binat, Khartoum",
                'achievements'      => null,
                'photo'             => 'assets/images/leadership/commissioner-sarah.jpg',
                'facebook_url'      => null,
                'twitter_url'       => null,
                'linkedin_url'      => null,
                'website_url'       => null,
                'years_of_service'  => 3,
                'department'        => null,
                'order_num'         => 7,
                'featured'          => false,
                'status'            => 'active',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Hon. Manuel Makum Matuop',
                'title'             => 'Hon.',
                'gender'            => 'male',
                'position'          => 'Commissioner',
                'date_of_birth'     => '1986-01-01',
                'nationality'       => 'South Sudanese',
                'email'             => 'commissioner.matuop@nec.gov.ss',
                'phone'             => '+211 912 000 008',
                'bio'               => 'NEC Commissioner from Mayom, Unity State, with a strong academic career in community studies.',
                'about'             => 'Hon. Manuel Makum Matuop was born in Mayom, Unity State, in 1986. He attended Comboni Primary School in Khartoum and graduated with a Certificate of Secondary Education from St. Augustine Secondary School (2011). He earned a Bachelor (Hons.) in Community Studies and Rural Development from the University of Bahr el-Ghazal and an M.Sc. in Community Studies and Rural Development (2024) from the University of Juba.',
                'experience'        => "Commissioner, National Elections Commission",
                'qualifications'    => "M.Sc. in Community Studies and Rural Development, University of Juba (2024)\nBachelor (Hons.) in Community Studies and Rural Development\nCertificate of Secondary Education, St. Augustine Secondary School (2011)",
                'achievements'      => null,
                'photo'             => 'assets/images/leadership/commissioner-manuel.jpg',
                'facebook_url'      => null,
                'twitter_url'       => null,
                'linkedin_url'      => null,
                'website_url'       => null,
                'years_of_service'  => null,
                'department'        => null,
                'order_num'         => 8,
                'featured'          => false,
                'status'            => 'active',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Hon. William Kolyin Deng',
                'title'             => 'Hon.',
                'gender'            => 'male',
                'position'          => 'Commissioner',
                'date_of_birth'     => '1964-01-01',
                'nationality'       => 'South Sudanese',
                'email'             => 'commissioner.wdeng@nec.gov.ss',
                'phone'             => '+211 912 000 009',
                'bio'               => 'NEC Commissioner appointed on 3 January 2023, a career educator.',
                'about'             => 'Hon. William Kolyin Deng was born in Ram-Ater, Cueibet County, Lakes State, in 1964. He graduated with a technical diploma from the teachers\' institute in Shendi locality, River Nile State, and continued to teach at high schools in Gezira State. He later graduated with a Bachelor of Education at the Sudan Open University. In 2009 he returned to South Sudan and served as General Headmaster of Gulu Secondary School in Rumbek and later of Cueibet Secondary School, until his appointment to the National Elections Commission on January 3, 2023.',
                'experience'        => "Commissioner, National Elections Commission (January 2023 – Present)\nGeneral Headmaster, Gulu and Cueibet Secondary Schools",
                'qualifications'    => "Bachelor of Education, Sudan Open University\nTechnical diploma, Teachers' Institute, Shendi (1989)",
                'achievements'      => null,
                'photo'             => 'assets/images/leadership/commissioner-william.jpg',
                'facebook_url'      => null,
                'twitter_url'       => null,
                'linkedin_url'      => null,
                'website_url'       => null,
                'years_of_service'  => 3,
                'department'        => null,
                'order_num'         => 9,
                'featured'          => false,
                'status'            => 'active',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ];

        DB::table('nec_commissioners')->insert($commissioners);
    }
}