<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CommissionerSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('nec_commissioners')->truncate();

        $commissioners = [
            [
                'name'              => 'Hon. Prof. Abednego A. A. Akok',
                'title'             => 'Prof.',
                'gender'            => 'male',
                'position'          => 'Chairperson',
                'date_of_birth'     => '1965-03-15',
                'nationality'       => 'South Sudanese',
                'email'             => 'chairperson@nec.gov.ss',
                'phone'             => '+211 912 000 001',
                'bio'               => 'Appointed as Chairperson of NEC with extensive experience in public administration and electoral management.',
                'about'             => 'Prof. Abednego A. A. Akok is a distinguished academic and public administrator who has dedicated over three decades to the service of South Sudan. As Chairperson of the National Elections Commission, he leads the institution responsible for organizing and supervising free, fair, and transparent elections across the nation. His leadership has been instrumental in strengthening democratic institutions and promoting civic participation in South Sudan.',
                'experience'        => "Chairperson, National Elections Commission (2021–Present)\nProfessor of Public Administration, University of Juba (2010–2021)\nDean, Faculty of Social Sciences, University of Juba (2005–2010)\nSenior Advisor, Ministry of Parliamentary Affairs (2003–2005)\nResearch Fellow, African Leadership Centre, Nairobi (2001–2003)",
                'qualifications'    => "Ph.D. in Public Administration – University of Nairobi\nMaster of Public Administration (MPA) – Harvard Kennedy School\nBachelor of Arts in Political Science – University of Juba\nFellow, Institute of Management Consultants (FIMC)\nCertified Electoral Management Professional – International IDEA",
                'achievements'      => "Led the successful organization of the 2024 National Elections\nStrengthened NEC's institutional capacity across all 32 states\nEstablished partnerships with international election monitoring bodies\nPublished over 40 academic papers on governance and electoral systems\nRecipient of the South Sudan National Service Medal (2022)",
                'photo'             => 'assets/images/chairperson.webp',
                'facebook_url'      => 'https://facebook.com/abednego.akok',
                'twitter_url'       => 'https://twitter.com/abednego_akok',
                'linkedin_url'      => 'https://linkedin.com/in/abednego-akok',
                'website_url'       => null,
                'years_of_service'  => 5,
                'department'        => 'Executive Office',
                'order_num'         => 1,
                'featured'          => true,
                'status'            => 'active',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'name'              => 'Hon. Sarah N. Wani',
                'title'             => 'Hon.',
                'gender'            => 'female',
                'position'          => 'Deputy Chairperson',
                'date_of_birth'     => '1970-07-22',
                'nationality'       => 'South Sudanese',
                'email'             => 'deputy.chairperson@nec.gov.ss',
                'phone'             => '+211 912 000 002',
                'bio'               => 'Experienced legal professional and advocate for democratic governance and electoral integrity.',
                'about'             => 'Hon. Sarah N. Wani brings a wealth of legal expertise and a deep commitment to democratic principles to her role as Deputy Chairperson of the National Elections Commission. With over 20 years of experience in legal practice and governance, she has been a tireless advocate for electoral reform and the protection of voters\' rights across South Sudan.',
                'experience'        => "Deputy Chairperson, National Elections Commission (2021–Present)\nSenior Legal Advisor, Ministry of Justice and Constitutional Affairs (2016–2021)\nLegal Counsel, South Sudan Human Rights Commission (2012–2016)\nPartner, Wani & Associates Legal Practice (2008–2012)\nLecturer in Constitutional Law, University of Juba (2006–2012)",
                'qualifications'    => "LL.M. in International Human Rights Law – University of Oxford\nLL.B. (Hons) – University of Nairobi\nBar Qualification – Kenya School of Law\nCertified Mediator – Chartered Institute of Arbitrators\nCertificate in Election Law – International Foundation for Electoral Systems",
                'achievements'      => "Co-drafted the National Elections Act 2023\nLed NEC's legal reform program covering 32 state offices\nEstablished the NEC Ombudsman for electoral complaints\nTrained over 500 election officials in electoral law\nSpeaker at the International Conference on Electoral Justice (2023)",
                'photo'             => null,
                'facebook_url'      => 'https://facebook.com/sarah.wani',
                'twitter_url'       => 'https://twitter.com/sarah_wani',
                'linkedin_url'      => 'https://linkedin.com/in/sarah-wani',
                'website_url'       => null,
                'years_of_service'  => 5,
                'department'        => 'Executive Office',
                'order_num'         => 2,
                'featured'          => false,
                'status'            => 'active',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'name'              => 'Hon. James L. Maker',
                'title'             => 'Hon.',
                'gender'            => 'male',
                'position'          => 'Commissioner – Operations',
                'date_of_birth'     => '1968-11-03',
                'nationality'       => 'South Sudanese',
                'email'             => 'commissioner.operations@nec.gov.ss',
                'phone'             => '+211 912 000 003',
                'bio'               => 'Specialist in electoral operations and field coordination with decades of public service.',
                'about'             => 'Hon. James L. Maker is a seasoned electoral operations specialist with over 25 years of experience in public administration and field coordination. He oversees the day-to-day operations of the National Elections Commission, ensuring the smooth delivery of electoral services across all 32 states of South Sudan.',
                'experience'        => "Commissioner – Operations, NEC (2021–Present)\nDirector of Field Operations, NEC (2018–2021)\nRegional Coordinator, Relief and Reconciliation Commission (2014–2018)\nCounty Administrator, Central Equatoria State (2010–2014)\nProgramme Officer, UNMISS (2008–2010)",
                'qualifications'    => "Master of Business Administration (MBA) – Juba University\nBachelor of Commerce – University of Nairobi\nCertificate in Electoral Administration – Australian Electoral Commission\nProject Management Professional (PMP) – PMI\nDiploma in Public Administration – South Sudan Civil Service Institute",
                'achievements'      => "Deployed 3,284 polling stations across South Sudan\nLed the logistics team for the 2024 National Elections\nReduced voter registration processing time by 40%\nEstablished NEC's digital operations management system\nSupervised the creation of 102 constituency offices",
                'photo'             => null,
                'facebook_url'      => null,
                'twitter_url'       => null,
                'linkedin_url'      => 'https://linkedin.com/in/james-maker',
                'website_url'       => null,
                'years_of_service'  => 8,
                'department'        => 'Operations',
                'order_num'         => 3,
                'featured'          => false,
                'status'            => 'active',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'name'              => 'Hon. Dr. Mary A. Nyandeng',
                'title'             => 'Dr.',
                'gender'            => 'female',
                'position'          => 'Commissioner – Civic Education',
                'date_of_birth'     => '1972-05-18',
                'nationality'       => 'South Sudanese',
                'email'             => 'commissioner.education@nec.gov.ss',
                'phone'             => '+211 912 000 004',
                'bio'               => 'Academic and civil society leader with expertise in civic education and voter outreach.',
                'about'             => 'Hon. Dr. Mary A. Nyandeng is a renowned academic and civil society leader who has devoted her career to strengthening civic education and voter engagement in South Sudan. As Commissioner for Civic Education, she leads NEC\'s efforts to ensure that all citizens are informed about their electoral rights and responsibilities.',
                'experience'        => "Commissioner – Civic Education, NEC (2021–Present)\nDirector, Center for Civic Education, University of Juba (2015–2021)\nCountry Director, International Republican Institute – South Sudan (2012–2015)\nSenior Programme Manager, Carter Center – Sudan Program (2009–2012)\nLecturer in Political Science, University of Juba (2005–2009)",
                'qualifications'    => "Ph.D. in Political Science – University of Cape Town\nMaster of Arts in Democracy & Development – University of West Cape\nBachelor of Arts in Sociology – University of Juba\nCertificate in Electoral Education – International IDEA\nCertified Civic Education Trainer – NDI",
                'achievements'      => "Launched civic education programs reaching 4.5 million citizens\nEstablished NEC's community outreach network in all 32 states\nDeveloped multilingual voter education materials in 15 languages\nCreated the NEC Youth Engagement Program reaching 800,000 young voters\nPublished research on women's political participation in East Africa",
                'photo'             => null,
                'facebook_url'      => 'https://facebook.com/mary.nyandeng',
                'twitter_url'       => 'https://twitter.com/mary_nyandeng',
                'linkedin_url'      => 'https://linkedin.com/in/mary-nyandeng',
                'website_url'       => 'https://civiceducation.nec.gov.ss',
                'years_of_service'  => 5,
                'department'        => 'Civic Education',
                'order_num'         => 4,
                'featured'          => false,
                'status'            => 'active',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'name'              => 'Hon. John M. Deng',
                'title'             => 'Hon.',
                'gender'            => 'male',
                'position'          => 'Commissioner – International Relations',
                'date_of_birth'     => '1966-09-12',
                'nationality'       => 'South Sudanese',
                'email'             => 'commissioner.intl@nec.gov.ss',
                'phone'             => '+211 912 000 005',
                'bio'               => 'Former diplomat with extensive experience in international relations and election observation.',
                'about'             => 'Hon. John M. Deng is a former diplomat whose career spans over 30 years in international relations and diplomatic service. As Commissioner for International Relations at NEC, he strengthens the commission\'s partnerships with international organizations, election monitoring bodies, and diplomatic missions.',
                'experience'        => "Commissioner – International Relations, NEC (2021–Present)\nAmbassador of South Sudan to Kenya (2014–2020)\nDeputy Permanent Representative, South Sudan Mission to the UN (2011–2014)\nDirector of Multilateral Affairs, Ministry of Foreign Affairs (2008–2011)\nFirst Secretary, South Sudan Embassy in Uganda (2003–2008)\nPolitical Affairs Officer, IGAD Secretariat (2000–2003)",
                'qualifications'    => "Master of Arts in International Relations – Georgetown University\nBachelor of Arts in Diplomacy – United States International University\nCertificate in Election Observation – OSCE/ODIHR\nAdvanced Diploma in Diplomatic Studies – Diplomatic Academy of Vienna\nFellow, Royal Institute of International Affairs (Chatham House)",
                'achievements'      => "Established NEC partnerships with 25 international election organizations\nLed the international election observation coordination for 2024 elections\nNegotiated MOUs with AU, IGAD, and EU election observation missions\nRepresented NEC at 12 international electoral conferences\nBuilt NEC's capacity for international best practices in election management",
                'photo'             => null,
                'facebook_url'      => null,
                'twitter_url'       => 'https://twitter.com/john_deng',
                'linkedin_url'      => 'https://linkedin.com/in/john-deng',
                'website_url'       => null,
                'years_of_service'  => 5,
                'department'        => 'International Relations',
                'order_num'         => 5,
                'featured'          => false,
                'status'            => 'active',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'name'              => 'Hon. Rebecca N. Kiden',
                'title'             => 'Hon.',
                'gender'            => 'female',
                'position'          => 'Commissioner – Legal Affairs',
                'date_of_birth'     => '1974-01-28',
                'nationality'       => 'South Sudanese',
                'email'             => 'commissioner.legal@nec.gov.ss',
                'phone'             => '+211 912 000 006',
                'bio'               => 'Gender equality advocate with a strong background in human rights and legal affairs.',
                'about'             => 'Hon. Rebecca N. Kiden is a passionate advocate for gender equality and human rights, with a distinguished legal career spanning over two decades. As Commissioner for Legal Affairs at NEC, she oversees the legal framework governing elections, ensures compliance with electoral laws, and champions inclusive participation in the democratic process.',
                'experience'        => "Commissioner – Legal Affairs, NEC (2021–Present)\nSenior Legal Officer, South Sudan National Human Rights Commission (2015–2021)\nGender Advisor, UN Women – South Sudan (2012–2015)\nHuman Rights Lawyer, Amnesty International (2008–2012)\nLegal Practitioner, High Court of South Sudan (2005–2008)\nParalegal, Legal Aid Bureau, Juba (2002–2005)",
                'qualifications'    => "LL.M. in Human Rights Law – University of Pretoria\nLL.B. (Hons) – University of Juba\nCertificate in International Humanitarian Law – ICRC\nGender Mainstreaming Certificate – UN Women Training Centre\nCertificate in Electoral Dispute Resolution – IFES",
                'achievements'      => "Drafted NEC's gender policy ensuring 30% women's representation\nEstablished NEC's legal aid desk for electoral complaints\nLed the review of 12 electoral regulations and bylaws\nTrained 200 NEC staff on electoral law and dispute resolution\nReceived the South Sudan Women of Courage Award (2023)",
                'photo'             => null,
                'facebook_url'      => 'https://facebook.com/rebecca.kiden',
                'twitter_url'       => 'https://twitter.com/rebecca_kiden',
                'linkedin_url'      => 'https://linkedin.com/in/rebecca-kiden',
                'website_url'       => null,
                'years_of_service'  => 5,
                'department'        => 'Legal Affairs',
                'order_num'         => 6,
                'featured'          => false,
                'status'            => 'active',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
        ];

        DB::table('nec_commissioners')->insert($commissioners);
    }
}
