<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    // [name, code(2), iso3(3), nationality, continent, calling_code]
    private array $countries = [
        ['Afghanistan', 'AF', 'AFG', 'Afghan', 'Asia', '93'],
        ['Albania', 'AL', 'ALB', 'Albanian', 'Europe', '355'],
        ['Algeria', 'DZ', 'DZA', 'Algerian', 'Africa', '213'],
        ['Andorra', 'AD', 'AND', 'Andorran', 'Europe', '376'],
        ['Angola', 'AO', 'AGO', 'Angolan', 'Africa', '244'],
        ['Antigua and Barbuda', 'AG', 'ATG', 'Antiguan and Barbudan', 'North America', '1'],
        ['Argentina', 'AR', 'ARG', 'Argentine', 'South America', '54'],
        ['Armenia', 'AM', 'ARM', 'Armenian', 'Asia', '374'],
        ['Australia', 'AU', 'AUS', 'Australian', 'Oceania', '61'],
        ['Austria', 'AT', 'AUT', 'Austrian', 'Europe', '43'],
        ['Azerbaijan', 'AZ', 'AZE', 'Azerbaijani', 'Asia', '994'],
        ['Bahamas', 'BS', 'BHS', 'Bahamian', 'North America', '1'],
        ['Bahrain', 'BH', 'BHR', 'Bahraini', 'Asia', '973'],
        ['Bangladesh', 'BD', 'BGD', 'Bangladeshi', 'Asia', '880'],
        ['Barbados', 'BB', 'BRB', 'Barbadian', 'North America', '1'],
        ['Belarus', 'BY', 'BLR', 'Belarusian', 'Europe', '375'],
        ['Belgium', 'BE', 'BEL', 'Belgian', 'Europe', '32'],
        ['Belize', 'BZ', 'BLZ', 'Belizean', 'North America', '501'],
        ['Benin', 'BJ', 'BEN', 'Beninese', 'Africa', '229'],
        ['Bhutan', 'BT', 'BTN', 'Bhutanese', 'Asia', '975'],
        ['Bolivia', 'BO', 'BOL', 'Bolivian', 'South America', '591'],
        ['Bosnia and Herzegovina', 'BA', 'BIH', 'Bosnian and Herzegovinian', 'Europe', '387'],
        ['Botswana', 'BW', 'BWA', 'Botswanan', 'Africa', '267'],
        ['Brazil', 'BR', 'BRA', 'Brazilian', 'South America', '55'],
        ['Brunei', 'BN', 'BRN', 'Bruneian', 'Asia', '673'],
        ['Bulgaria', 'BG', 'BGR', 'Bulgarian', 'Europe', '359'],
        ['Burkina Faso', 'BF', 'BFA', 'Burkinabé', 'Africa', '226'],
        ['Burundi', 'BI', 'BDI', 'Burundian', 'Africa', '257'],
        ['Cambodia', 'KH', 'KHM', 'Cambodian', 'Asia', '855'],
        ['Cameroon', 'CM', 'CMR', 'Cameroonian', 'Africa', '237'],
        ['Canada', 'CA', 'CAN', 'Canadian', 'North America', '1'],
        ['Cape Verde', 'CV', 'CPV', 'Cape Verdean', 'Africa', '238'],
        ['Central African Republic', 'CF', 'CAF', 'Central African', 'Africa', '236'],
        ['Chad', 'TD', 'TCD', 'Chadian', 'Africa', '235'],
        ['Chile', 'CL', 'CHL', 'Chilean', 'South America', '56'],
        ['China', 'CN', 'CHN', 'Chinese', 'Asia', '86'],
        ['Colombia', 'CO', 'COL', 'Colombian', 'South America', '57'],
        ['Comoros', 'KM', 'COM', 'Comorian', 'Africa', '269'],
        ['Congo DR', 'CD', 'COD', 'Congolese', 'Africa', '243'],
        ['Congo Republic', 'CG', 'COG', 'Congolese', 'Africa', '242'],
        ['Costa Rica', 'CR', 'CRI', 'Costa Rican', 'North America', '506'],
        ['Côte d\'Ivoire', 'CI', 'CIV', 'Ivorian', 'Africa', '225'],
        ['Croatia', 'HR', 'HRV', 'Croatian', 'Europe', '385'],
        ['Cuba', 'CU', 'CUB', 'Cuban', 'North America', '53'],
        ['Cyprus', 'CY', 'CYP', 'Cypriot', 'Asia', '357'],
        ['Czech Republic', 'CZ', 'CZE', 'Czech', 'Europe', '420'],
        ['Denmark', 'DK', 'DNK', 'Danish', 'Europe', '45'],
        ['Djibouti', 'DJ', 'DJI', 'Djiboutian', 'Africa', '253'],
        ['Dominica', 'DM', 'DMA', 'Dominican', 'North America', '1'],
        ['Dominican Republic', 'DO', 'DOM', 'Dominican', 'North America', '1'],
        ['East Timor', 'TL', 'TLS', 'Timorese', 'Asia', '670'],
        ['Ecuador', 'EC', 'ECU', 'Ecuadorian', 'South America', '593'],
        ['Egypt', 'EG', 'EGY', 'Egyptian', 'Africa', '20'],
        ['El Salvador', 'SV', 'SLV', 'Salvadoran', 'North America', '503'],
        ['Equatorial Guinea', 'GQ', 'GNQ', 'Equatorial Guinean', 'Africa', '240'],
        ['Eritrea', 'ER', 'ERI', 'Eritrean', 'Africa', '291'],
        ['Estonia', 'EE', 'EST', 'Estonian', 'Europe', '372'],
        ['Eswatini', 'SZ', 'SWZ', 'Swazi', 'Africa', '268'],
        ['Ethiopia', 'ET', 'ETH', 'Ethiopian', 'Africa', '251'],
        ['Fiji', 'FJ', 'FJI', 'Fijian', 'Oceania', '679'],
        ['Finland', 'FI', 'FIN', 'Finnish', 'Europe', '358'],
        ['France', 'FR', 'FRA', 'French', 'Europe', '33'],
        ['Gabon', 'GA', 'GAB', 'Gabonese', 'Africa', '241'],
        ['Gambia', 'GM', 'GMB', 'Gambian', 'Africa', '220'],
        ['Georgia', 'GE', 'GEO', 'Georgian', 'Asia', '995'],
        ['Germany', 'DE', 'DEU', 'German', 'Europe', '49'],
        ['Ghana', 'GH', 'GHA', 'Ghanaian', 'Africa', '233'],
        ['Greece', 'GR', 'GRC', 'Greek', 'Europe', '30'],
        ['Grenada', 'GD', 'GRD', 'Grenadian', 'North America', '1'],
        ['Guatemala', 'GT', 'GTM', 'Guatemalan', 'North America', '502'],
        ['Guinea', 'GN', 'GIN', 'Guinean', 'Africa', '224'],
        ['Guinea-Bissau', 'GW', 'GNB', 'Bissau-Guinean', 'Africa', '245'],
        ['Guyana', 'GY', 'GUY', 'Guyanese', 'South America', '592'],
        ['Haiti', 'HT', 'HTI', 'Haitian', 'North America', '509'],
        ['Honduras', 'HN', 'HND', 'Honduran', 'North America', '504'],
        ['Hungary', 'HU', 'HUN', 'Hungarian', 'Europe', '36'],
        ['Iceland', 'IS', 'ISL', 'Icelandic', 'Europe', '354'],
        ['India', 'IN', 'IND', 'Indian', 'Asia', '91'],
        ['Indonesia', 'ID', 'IDN', 'Indonesian', 'Asia', '62'],
        ['Iran', 'IR', 'IRN', 'Iranian', 'Asia', '98'],
        ['Iraq', 'IQ', 'IRQ', 'Iraqi', 'Asia', '964'],
        ['Ireland', 'IE', 'IRL', 'Irish', 'Europe', '353'],
        ['Israel', 'IL', 'ISR', 'Israeli', 'Asia', '972'],
        ['Italy', 'IT', 'ITA', 'Italian', 'Europe', '39'],
        ['Jamaica', 'JM', 'JAM', 'Jamaican', 'North America', '1'],
        ['Japan', 'JP', 'JPN', 'Japanese', 'Asia', '81'],
        ['Jordan', 'JO', 'JOR', 'Jordanian', 'Asia', '962'],
        ['Kazakhstan', 'KZ', 'KAZ', 'Kazakhstani', 'Asia', '7'],
        ['Kenya', 'KE', 'KEN', 'Kenyan', 'Africa', '254'],
        ['Kiribati', 'KI', 'KIR', 'Kiribati', 'Oceania', '686'],
        ['Kosovo', 'XK', 'XKX', 'Kosovar', 'Europe', '383'],
        ['Kuwait', 'KW', 'KWT', 'Kuwaiti', 'Asia', '965'],
        ['Kyrgyzstan', 'KG', 'KGZ', 'Kyrgyzstani', 'Asia', '996'],
        ['Laos', 'LA', 'LAO', 'Laotian', 'Asia', '856'],
        ['Latvia', 'LV', 'LVA', 'Latvian', 'Europe', '371'],
        ['Lebanon', 'LB', 'LBN', 'Lebanese', 'Asia', '961'],
        ['Lesotho', 'LS', 'LSO', 'Mosotho', 'Africa', '266'],
        ['Liberia', 'LR', 'LBR', 'Liberian', 'Africa', '231'],
        ['Libya', 'LY', 'LBY', 'Libyan', 'Africa', '218'],
        ['Liechtenstein', 'LI', 'LIE', 'Liechtensteiner', 'Europe', '423'],
        ['Lithuania', 'LT', 'LTU', 'Lithuanian', 'Europe', '370'],
        ['Luxembourg', 'LU', 'LUX', 'Luxembourger', 'Europe', '352'],
        ['Madagascar', 'MG', 'MDG', 'Malagasy', 'Africa', '261'],
        ['Malawi', 'MW', 'MWI', 'Malawian', 'Africa', '265'],
        ['Malaysia', 'MY', 'MYS', 'Malaysian', 'Asia', '60'],
        ['Maldives', 'MV', 'MDV', 'Maldivian', 'Asia', '960'],
        ['Mali', 'ML', 'MLI', 'Malian', 'Africa', '223'],
        ['Malta', 'MT', 'MLT', 'Maltese', 'Europe', '356'],
        ['Marshall Islands', 'MH', 'MHL', 'Marshallese', 'Oceania', '692'],
        ['Mauritania', 'MR', 'MRT', 'Mauritanian', 'Africa', '222'],
        ['Mauritius', 'MU', 'MUS', 'Mauritian', 'Africa', '230'],
        ['Mexico', 'MX', 'MEX', 'Mexican', 'North America', '52'],
        ['Micronesia', 'FM', 'FSM', 'Micronesian', 'Oceania', '691'],
        ['Moldova', 'MD', 'MDA', 'Moldovan', 'Europe', '373'],
        ['Monaco', 'MC', 'MCO', 'Monacan', 'Europe', '377'],
        ['Mongolia', 'MN', 'MNG', 'Mongolian', 'Asia', '976'],
        ['Montenegro', 'ME', 'MNE', 'Montenegrin', 'Europe', '382'],
        ['Morocco', 'MA', 'MAR', 'Moroccan', 'Africa', '212'],
        ['Mozambique', 'MZ', 'MOZ', 'Mozambican', 'Africa', '258'],
        ['Myanmar', 'MM', 'MMR', 'Burmese', 'Asia', '95'],
        ['Namibia', 'NA', 'NAM', 'Namibian', 'Africa', '264'],
        ['Nauru', 'NR', 'NRU', 'Nauruan', 'Oceania', '674'],
        ['Nepal', 'NP', 'NPL', 'Nepali', 'Asia', '977'],
        ['Netherlands', 'NL', 'NLD', 'Dutch', 'Europe', '31'],
        ['New Zealand', 'NZ', 'NZL', 'New Zealander', 'Oceania', '64'],
        ['Nicaragua', 'NI', 'NIC', 'Nicaraguan', 'North America', '505'],
        ['Niger', 'NE', 'NER', 'Nigerien', 'Africa', '227'],
        ['Nigeria', 'NG', 'NGA', 'Nigerian', 'Africa', '234'],
        ['North Korea', 'KP', 'PRK', 'North Korean', 'Asia', '850'],
        ['North Macedonia', 'MK', 'MKD', 'Macedonian', 'Europe', '389'],
        ['Norway', 'NO', 'NOR', 'Norwegian', 'Europe', '47'],
        ['Oman', 'OM', 'OMN', 'Omani', 'Asia', '968'],
        ['Pakistan', 'PK', 'PAK', 'Pakistani', 'Asia', '92'],
        ['Palau', 'PW', 'PLW', 'Palauan', 'Oceania', '680'],
        ['Palestine', 'PS', 'PSE', 'Palestinian', 'Asia', '970'],
        ['Panama', 'PA', 'PAN', 'Panamanian', 'North America', '507'],
        ['Papua New Guinea', 'PG', 'PNG', 'Papua New Guinean', 'Oceania', '675'],
        ['Paraguay', 'PY', 'PRY', 'Paraguayan', 'South America', '595'],
        ['Peru', 'PE', 'PER', 'Peruvian', 'South America', '51'],
        ['Philippines', 'PH', 'PHL', 'Filipino', 'Asia', '63'],
        ['Poland', 'PL', 'POL', 'Polish', 'Europe', '48'],
        ['Portugal', 'PT', 'PRT', 'Portuguese', 'Europe', '351'],
        ['Qatar', 'QA', 'QAT', 'Qatari', 'Asia', '974'],
        ['Romania', 'RO', 'ROU', 'Romanian', 'Europe', '40'],
        ['Russia', 'RU', 'RUS', 'Russian', 'Europe', '7'],
        ['Rwanda', 'RW', 'RWA', 'Rwandan', 'Africa', '250'],
        ['Saint Kitts and Nevis', 'KN', 'KNA', 'Kittitian and Nevisian', 'North America', '1'],
        ['Saint Lucia', 'LC', 'LCA', 'Saint Lucian', 'North America', '1'],
        ['Saint Vincent and the Grenadines', 'VC', 'VCT', 'Vincentian', 'North America', '1'],
        ['Samoa', 'WS', 'WSM', 'Samoan', 'Oceania', '685'],
        ['San Marino', 'SM', 'SMR', 'Sammarinese', 'Europe', '378'],
        ['Sao Tome and Principe', 'ST', 'STP', 'São Toméan', 'Africa', '239'],
        ['Saudi Arabia', 'SA', 'SAU', 'Saudi', 'Asia', '966'],
        ['Senegal', 'SN', 'SEN', 'Senegalese', 'Africa', '221'],
        ['Serbia', 'RS', 'SRB', 'Serbian', 'Europe', '381'],
        ['Seychelles', 'SC', 'SYC', 'Seychellois', 'Africa', '248'],
        ['Sierra Leone', 'SL', 'SLE', 'Sierra Leonean', 'Africa', '232'],
        ['Singapore', 'SG', 'SGP', 'Singaporean', 'Asia', '65'],
        ['Slovakia', 'SK', 'SVK', 'Slovak', 'Europe', '421'],
        ['Slovenia', 'SI', 'SVN', 'Slovene', 'Europe', '386'],
        ['Solomon Islands', 'SB', 'SLB', 'Solomon Islander', 'Oceania', '677'],
        ['Somalia', 'SO', 'SOM', 'Somali', 'Africa', '252'],
        ['South Africa', 'ZA', 'ZAF', 'South African', 'Africa', '27'],
        ['South Korea', 'KR', 'KOR', 'South Korean', 'Asia', '82'],
        ['South Sudan', 'SS', 'SSD', 'South Sudanese', 'Africa', '211'],
        ['Spain', 'ES', 'ESP', 'Spanish', 'Europe', '34'],
        ['Sri Lanka', 'LK', 'LKA', 'Sri Lankan', 'Asia', '94'],
        ['Sudan', 'SD', 'SDN', 'Sudanese', 'Africa', '249'],
        ['Suriname', 'SR', 'SUR', 'Surinamese', 'South America', '597'],
        ['Sweden', 'SE', 'SWE', 'Swedish', 'Europe', '46'],
        ['Switzerland', 'CH', 'CHE', 'Swiss', 'Europe', '41'],
        ['Syria', 'SY', 'SYR', 'Syrian', 'Asia', '963'],
        ['Taiwan', 'TW', 'TWN', 'Taiwanese', 'Asia', '886'],
        ['Tajikistan', 'TJ', 'TJK', 'Tajikistani', 'Asia', '992'],
        ['Tanzania', 'TZ', 'TZA', 'Tanzanian', 'Africa', '255'],
        ['Thailand', 'TH', 'THA', 'Thai', 'Asia', '66'],
        ['Togo', 'TG', 'TGO', 'Togolese', 'Africa', '228'],
        ['Tonga', 'TO', 'TON', 'Tongan', 'Oceania', '676'],
        ['Trinidad and Tobago', 'TT', 'TTO', 'Trinidadian and Tobagonian', 'North America', '1'],
        ['Tunisia', 'TN', 'TUN', 'Tunisian', 'Africa', '216'],
        ['Turkey', 'TR', 'TUR', 'Turkish', 'Asia', '90'],
        ['Turkmenistan', 'TM', 'TKM', 'Turkmen', 'Asia', '993'],
        ['Tuvalu', 'TV', 'TUV', 'Tuvaluan', 'Oceania', '688'],
        ['Uganda', 'UG', 'UGA', 'Ugandan', 'Africa', '256'],
        ['Ukraine', 'UA', 'UKR', 'Ukrainian', 'Europe', '380'],
        ['United Arab Emirates', 'AE', 'ARE', 'Emirati', 'Asia', '971'],
        ['United Kingdom', 'GB', 'GBR', 'British', 'Europe', '44'],
        ['United States', 'US', 'USA', 'American', 'North America', '1'],
        ['Uruguay', 'UY', 'URY', 'Uruguayan', 'South America', '598'],
        ['Uzbekistan', 'UZ', 'UZB', 'Uzbek', 'Asia', '998'],
        ['Vanuatu', 'VU', 'VUT', 'Ni-Vanuatu', 'Oceania', '678'],
        ['Vatican City', 'VA', 'VAT', 'Vatican', 'Europe', '379'],
        ['Venezuela', 'VE', 'VEN', 'Venezuelan', 'South America', '58'],
        ['Vietnam', 'VN', 'VNM', 'Vietnamese', 'Asia', '84'],
        ['Yemen', 'YE', 'YEM', 'Yemeni', 'Asia', '967'],
        ['Zambia', 'ZM', 'ZMB', 'Zambian', 'Africa', '260'],
        ['Zimbabwe', 'ZW', 'ZWE', 'Zimbabwean', 'Africa', '263'],
    ];

    public function run(): void
    {
        $now = now();
        $existing = DB::table('nec_countries')->pluck('code')->map(fn($c) => strtoupper($c))->toArray();

        $inserted = 0;
        foreach ($this->countries as $row) {
            [$name, $code, $iso3, $nationality, $continent, $calling] = $row;
            if (in_array(strtoupper($code), $existing)) {
                continue;
            }
            DB::table('nec_countries')->updateOrInsert(
                ['code' => strtoupper($code)],
                [
                    'name' => $name,
                    'code' => strtoupper($code),
                    'iso3' => strtoupper($iso3),
                    'nationality' => $nationality,
                    'continent' => $continent,
                    'calling_code' => $calling,
                    'status' => 'active',
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
            $inserted++;
        }

        $this->command->info("CountriesSeeder: {$inserted} countries inserted, total: " . DB::table('nec_countries')->count());
    }
}